name: 'MASS Release Notes Action'
description: 'This action aggregates release notes across several repositories.'
inputs:
  release_tag:
    description: 'Tag of release just built.'
    required: true
  pre_release:
    description: 'Stable or beta.'
    required: true  
  github_token:
    description: 'The GitHub API access token to use for authentication.'
    required: true
branding:
  icon: 'box'
  color: 'purple'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --release_tag=${{ inputs.release_tag }}
    - --github_token=${{ inputs.github_token }}
    - --pre_release=${{ inputs.pre_release }}