name: 'MASS Release Notes Action'
description: 'This action aggregates release notes across several repositories.'
inputs:
  pre_release:
    description: 'Whether or not this is a pre-release.'
    required: true
  github_token:
    description: 'The GitHub API access token to use for authentication.'
    required: true
branding:
  icon: 'box'
  color: 'purple'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --pre_release=${{ inputs.pre_release }}
    - --github_token=${{ inputs.github_token }}