name: 'Release Notes Merge Action'
on:
  workflow_dispatch:
    inputs:
        pre_release:
          description: 'Is this a pre-release?'
          required: true
          default: 'true'
        new_frontend_tag:
          description: 'New frontend tag'
          required: false
          default: ''
    
jobs:
  merge-and-release:
    runs-on: ubuntu-latest
    steps:  
      - uses: music-assistant/release-notes-merge-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pre_release: ${{ inputs.pre_release }}