name: 'Release Notes Merge Action'
on:
  workflow_dispatch:
    inputs:
      pre_release:
        description: 'Is this a pre-release?'
        required: true
        default: 'false'
      new_frontend_tag:
        description: 'New frontend tag'
        required: true
        default: 'false'
      new_frontend_release_title:
        description: 'New frontend release title'
        required: true
        default: 'false'
      new_server_tag:
        description: 'New server tag'
        required: true
        default: 'false'
      new_server_release_title:
        description: 'New server release title'
        required: true
        default: 'false'
    
jobs:
  do_releases:
    runs-on: ubuntu-latest
    steps:  
      - uses: jozefKruszynski/release-notes-merge-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 